"$schema" = 'https://starship.rs/config-schema.json'

format = '$username$hostname$character$directory'
add_newline = true
scan_timeout = 10
right_format = '$terraform$git_state$git_status$git_branch$git_commit${custom.rad}$battery'

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[character]
success_symbol = '[â–²](white)'
error_symbol = '[â–²](red)'
vicmd_symbol = '[â–³](blue)'

[directory]
truncation_length = 3
truncation_symbol = 'â€¦/'
style = 'blue dimmed'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
rebase = '[rebasing](bold magenta)'
merge = '[merging](bold yellow)'
revert = '[reverting](bold blue)'
cherry_pick = '[picking](bold red)'
bisect = '[bisecting](bold red)'
am = '[applying](bold green)'
am_or_rebase = '[applying/rebasing](bold yellow)'

[git_status]
format = '([$all_status $ahead_behind]($style) )'
style = '8'
up_to_date = 'î‚ '
untracked = '.'
conflicted = '#'
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'â‡•'
stashed = '^'
modified = '*'
staged = '+'
renamed = 'Â»'
deleted = 'x'

[line_break]
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
style = '8'
truncation_length = 16
truncation_symbol = ''
ignore_branches = []
symbol = "ï˜ "

[git_commit]
format = ' [$hash$tag]($style)'
style = '8'
only_detached = false
commit_hash_length = 6
tag_symbol = ''

[terraform] 
format = '[$symbol$workspace]($style) '
style = '105'
symbol = 'îšš '

[battery]
full_symbol = 'ğŸ”‹'
charging_symbol = 'âš¡ï¸'
discharging_symbol = 'ğŸ”‹'
empty_symbol = '\[ \]'
unknown_symbol = '\[?\]'
format = ' [$percentage](black) [$symbol]($style)'
[[battery.display]]
threshold = 35
style = 'yellow'
discharging_symbol = 'ğŸª«'

[custom.rad]
command = 'rad inspect --rid'
require_repo = true
when = true
format = ' [$symbol($output )]($style)'
style = '#8585FF'

[hostname]
ssh_only = false
format = '@[$hostname](bold red)[$ssh_symbol](bold blue) '
disabled = false
aliases = { "ubuntu-8gb-hil-1" = "hetzner" }
ssh_symbol = "î¬ "

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false
